tosca_definitions_version: tosca_simple_yaml_1_3

imports:
  - nodetypes/VM/RemoteWorkstation/NodeType.yaml
  - nodetypes/Docker/DockerEngineUbuntu/NodeType.yaml  
  - nodetypes/Docker/container/NodeType.yaml

topology_template:
  node_templates:
  
    RemoteWorkstation_VM:
      type: VM.RemoteWorkstation
      properties:
        ssh_username: "ubuntu"
        KeyFile: "/home/ubuntu/.ssh/chinmayadehury"
        external_ip: "172.17.91.195"

    DockerEngine:
      type: docker.DockerEngineUbuntu
      requirements:
        - host:
            node: RemoteWorkstation_VM

    containerNginx:
      type: docker.container
      properties:
        container_port: 80
        image_name: "nginx:1.13"
        container_name: "testingNginx"
        host_port: 8080        
      requirements:
        - host:
            node: DockerEngine
    
    containerHttp:
      type: docker.container
      properties:
        container_port: 80
        image_name: "httpd:2.4"
        container_name: "testingHttp"
        host_port: 8081        
      requirements:
        - host:
            node: DockerEngine
    