---
- name: create
  hosts: all
  gather_facts: true
  become: true
  become_method: sudo
  vars:
    ansible_ssh_private_key_file: "{{ KeyFile }}"
    ansible_ssh_user: "{{ssh_username}}"

  tasks:
    - name: Create a directory that will contain your data in persistent way
      file:
        path: "{{ data_dir }}/grafana/data"
        state: directory
        owner: 472
        group: 472
        recurse: yes       
    
    - name: Start container 
      docker_container:
        name: "{{container_name}}"
        image: "grafana/grafana"
        ports:
          - "{{host_port }}:3000" 
        env:
          GF_SECURITY_ADMIN_USER: "{{username}}"
          GF_SECURITY_ADMIN_PASSWORD: "{{password}}"
        volumes:
          -  "{{ data_dir }}/grafana/data:/var/lib/grafana"        
        state: started